Algoritmo "idadeex2"

Var
   prim_Nome, seg_Nome: caractere
   idade1, idade2: inteiro
   media: real


Inicio
)
   escreval("Dados da primeira pessoa: ")
   escreval("Nome: " )
   leia(prim_Nome)
   escreval("Idade: ")
   leia(idade1)
   escreval("Dados da segunda pessoa: ")
   escreval("Nome: ")
   leia(seg_Nome)
   escreval("Idade: ")
   leia(idade2)
   media <- (idade1 + idade2)/2
   escreva("A media de ", prim_Nome," e ", seg_Nome," e de ", media:4:1," anos")



Fimalgoritmo